name: Build and release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn package

      - name: Define tag name
        env:
          TZ: 'Asia/Tokyo'
        run: echo "RELEASE_TAG=v$(date '+%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}

      - name: Upload assets
        run: |
          gh release upload ${{ env.RELEASE_TAG }} sintyoku.jar --clobber
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
